### ISSUE TITLE
ToDo

### ISSUE THREAD

**Issue by xCrashsystemx** [mostafakanaan/DBWT_19-20#1]
- [x] fix footer on produkte.php

- [x] add details.php

- [x] start.php final touch 

- [x] center footer links

**Comment by xCrashsystemx** [comment]
- [ ] fix textarea details.php

- [ ] fix rating form

**Comment by mostafakanaan** [comment]
@xCrashsystemx textarea?
